### ISSUE TITLE
Something I noticed

### ISSUE THREAD

**Issue by dillfrescott** [prophesier/diff-svc#18]
Setting `use_gt_mel` to `True` seems to yield much better results than setting it to `False`, especially at lower steps. Why is this?

**Comment by dillfrescott** [comment]
At high steps they are nearly identical, with it on `True` still sounding better at almost 170k steps

**Comment by prophesier** [comment]
I only performed test of `use_gt_mel` on models at large steps, and did not notice obvious difference. However, it's not surprising that it will yield better results. Because it will use the ground-truth mel spectrum of your input audio, and the price is the characteristic feature similarity between the output audio and your target speaker.

**Comment by dillfrescott** [comment]
Ah, gotcha!
